"""Render the governed Python API manifest as a readable Markdown reference."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "docs" / "public-api.json"
REFERENCE = ROOT / "docs" / "API_REFERENCE.md"


def render(manifest: Path = MANIFEST) -> str:
    """Return the deterministic Markdown projection of the governed manifest."""
    document = json.loads(manifest.read_text(encoding="utf-8"))
    lines = [
        "# Governed Python API Reference",
        "",
        "<!-- Generated by scripts/render_public_api_reference.py; do not edit manually. -->",
        "",
        "This is the complete, generated reference for the public names governed by",
        "[`public-api.json`](public-api.json). `docs/PUBLIC_API.md` owns stability",
        "policy and compatibility expectations; this page is an inventory only.",
        "",
        "Regenerate it with:",
        "",
        "```bash",
        "uv run python scripts/render_public_api_reference.py",
        "```",
        "",
        "Use `--check` in automation to verify that this projection has not drifted.",
    ]

    for distribution in document["distributions"]:
        lines.extend(("", f"## `{distribution['distribution']}`", ""))
        for module in distribution["modules"]:
            lines.extend((f"### `{module['module']}`", ""))
            if not module["exports"]:
                lines.extend(("This module currently exports no public names.", ""))
                continue
            lines.extend(("| Name | Stability |", "| --- | --- |"))
            lines.extend(
                f"| `{entry['name']}` | `{entry['stability']}` |" for entry in module["exports"]
            )
            lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail when the checked-in reference drifts"
    )
    args = parser.parse_args()

    expected = render()
    if args.check:
        return 0 if REFERENCE.is_file() and REFERENCE.read_text(encoding="utf-8") == expected else 1

    REFERENCE.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
