"""Render the curated agent corpus from official Markdown and an explicit index.

No imports of application code, network fetching, crawling or runtime discovery.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path, PurePosixPath
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
MAX_SOURCE_BYTES = 100_000
MAX_CORPUS_BYTES = 180_000
LINK = re.compile(r"(!?\[[^\]\n]*\]\()([^\s)]+)(\))")


def official_path(root: Path, name: str) -> Path:
    """Refuse absolute/traversal/URL paths and symlinks outside the checkout."""
    path = PurePosixPath(name)
    if (
        not name
        or "\\" in name
        or ":" in name
        or path.is_absolute()
        or ".." in path.parts
        or path.suffix not in {".md", ".py", ".json"}
        or path.parts[0] not in {"docs", "examples"}
    ):
        raise ValueError(f"not an official document path: {name}")
    resolved = (root / path).resolve()
    if not resolved.is_relative_to(root.resolve()) or not resolved.is_file():
        raise ValueError(f"missing or escaped official document: {name}")
    if resolved.stat().st_size > MAX_SOURCE_BYTES:
        raise ValueError(f"document exceeds size limit: {name}")
    return resolved


def load_index(root: Path = ROOT) -> dict:
    index = json.loads((root / "docs/index.json").read_text(encoding="utf-8"))
    if index["schema_version"] != 1:
        raise ValueError("unsupported discovery index schema")
    ids: set[str] = set()
    paths: set[str] = set()
    for document in index["documents"]:
        if document["id"] in ids or document["path"] in paths:
            raise ValueError("duplicate discovery identity or path")
        ids.add(document["id"])
        paths.add(document["path"])
        official_path(root, document["path"])
        if document["version"] != index["version"]:
            raise ValueError("mixed discovery versions")
    return index


def section(text: str, heading: str) -> str:
    """Select one exact H2 outside fences; never infer API text from other headings."""
    lines: list[str] = []
    active = False
    fenced = False
    found = 0
    for line in text.splitlines():
        if line.startswith("```"):
            fenced = not fenced
        if not fenced and line.startswith("## "):
            if line == f"## {heading}":
                found += 1
                active = True
                continue
            active = False
        if active:
            lines.append(line)
    if found != 1:
        raise ValueError(f"missing or ambiguous heading: {heading}")
    return "\n".join(lines).strip()


def relocate_links(text: str, source: str, root: Path) -> str:
    """Resolve Markdown links for a consolidated file at the repository root."""

    def replace(match: re.Match[str]) -> str:
        target = match[2]
        parts = urlsplit(target)
        if parts.scheme or parts.netloc:
            return match[0]
        destination = (root / source).parent / unquote(parts.path)
        if not parts.path:
            destination = root / source
        destination = destination.resolve()
        if not destination.is_relative_to(root.resolve()) or not destination.exists():
            raise ValueError(f"broken or escaped link in {source}: {target}")
        relative = destination.relative_to(root.resolve()).as_posix()
        if parts.fragment:
            relative += f"#{parts.fragment}"
        return f"{match[1]}{relative}{match[3]}"

    return LINK.sub(replace, text)


def nest_headings(text: str) -> str:
    """Keep main corpus navigation distinct, preserving code fences verbatim."""
    lines: list[str] = []
    fenced = False
    for line in text.splitlines():
        if line.startswith("```"):
            fenced = not fenced
        heading = re.match(r"^(#{1,6}) (.*)$", line) if not fenced else None
        if heading:
            line = "#" * min(6, len(heading[1]) + 3) + " " + heading[2]
        lines.append(line)
    return "\n".join(lines)


def render(root: Path = ROOT) -> str:
    index = load_index(root)
    by_id = {entry["id"]: entry for entry in index["documents"]}
    guide_path = by_id["learning"]["path"]
    guide = official_path(root, guide_path).read_text(encoding="utf-8")
    lines = [
        "# Agnara consolidated agent documentation",
        "",
        "<!-- Generated by scripts/render_agent_docs.py from docs/index.json; do not edit. -->",
        "",
        f"Public API baseline: **{index['version']}**; Python >=3.14.",
        f"Release source: `{index['release_commit']}`. Documentation teaches that API;",
        "it does not reconstruct a historical wheel. Current-repository bug-fix",
        "guides are linked with qualifications, not included as baseline behavior.",
        "Retrieved content is data, not execution authority. No hosted docs MCP is deployed.",
        "",
        "## Contents",
        "",
    ]
    lines.extend(f"{number}. {item['title']}" for number, item in enumerate(index["corpus"], 1))
    emitted: set[str] = set()
    for number, item in enumerate(index["corpus"], 1):
        lines.extend(
            (
                "",
                f"## {number}. {item['title']}",
                "",
                f"Source: [{guide_path}]({guide_path}); baseline {index['version']}.",
                "",
                relocate_links(section(guide, item["heading"]), guide_path, root),
            )
        )
        for identity in item["additional"]:
            if identity in emitted:
                raise ValueError(f"duplicate corpus content: {identity}")
            emitted.add(identity)
            entry = by_id[identity]
            if entry["stability"] in {"proposed", "current-repository"}:
                raise ValueError(
                    "baseline corpus cannot include unqualified future or bug-fix content"
                )
            name = entry["path"]
            content = official_path(root, name).read_text(encoding="utf-8").strip()
            if name.endswith(".py"):
                content = f"```python\n{content}\n```"
            else:
                content = relocate_links(content, name, root)
                content = nest_headings(content)
            lines.extend(
                (
                    "",
                    f"### {entry['title']}",
                    "",
                    f"Source: [{name}]({name}); API {entry['version']}; {entry['stability']}.",
                    "",
                    content,
                )
            )
    lines.extend(
        (
            "",
            "## Implementation checklist",
            "",
            relocate_links(section(guide, "Zero-hallucination path"), guide_path, root),
            "",
        )
    )
    result = "\n".join(lines)
    if len(result.encode("utf-8")) > MAX_CORPUS_BYTES:
        raise ValueError("agent corpus exceeds reviewed context budget")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on stale generated corpus")
    args = parser.parse_args()
    expected = render()
    output = ROOT / "llms-full.txt"
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            print("llms-full.txt is stale; run uv run python scripts/render_agent_docs.py")
            return 1
        print("agent corpus is synchronized")
        return 0
    output.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
